/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mohos
 */
public class UserMainFrame extends javax.swing.JFrame {
    PreparedStatement st;
    ResultSet rs;
    

    /**
     * Creates new form UserMainFrame
     */
    public UserMainFrame() {
        initComponents();
        setCalendar();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Home_bar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Profile_bar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Balance_check_bar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Loan_service_bar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Developer_bar = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Logout_bar = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        CalendarTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        BalanceCheckPanel = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TF_Balance = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CP_TF_PreAdd5 = new javax.swing.JTextField();
        jLabel86 = new javax.swing.JLabel();
        DeveloperPanel = new javax.swing.JPanel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        DeveloperPanel1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        CP_Panel = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        CP_TF_AccNo = new javax.swing.JTextField();
        CP_TF_AccTitle = new javax.swing.JTextField();
        CP_TF_AccHolder = new javax.swing.JTextField();
        CP_TF_ContNo = new javax.swing.JTextField();
        CP_TF_Nationality = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        CP_TF_Balance = new javax.swing.JTextField();
        CP_TF_SA = new javax.swing.JTextField();
        CP_TF_ParAdd = new javax.swing.JTextField();
        CP_TF_PreAdd = new javax.swing.JTextField();
        CP_TF_AccNo1 = new javax.swing.JTextField();
        CP_TF_AccNo2 = new javax.swing.JTextField();
        CP_TF_PreAdd1 = new javax.swing.JTextField();
        CP_TF_PreAdd2 = new javax.swing.JTextField();
        CP_TF_PreAdd3 = new javax.swing.JTextField();
        jLabel85 = new javax.swing.JLabel();
        CP_TF_PreAdd4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        RS_Panel = new javax.swing.JPanel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        RS_AccTitle = new javax.swing.JTextField();
        RS_ContNo = new javax.swing.JTextField();
        RS_Balance = new javax.swing.JTextField();
        RS_RP = new javax.swing.JTextField();
        BTN_Submit22 = new javax.swing.JButton();
        jLabel131 = new javax.swing.JLabel();
        RS_Stepend = new javax.swing.JTextField();
        RS_AccNo = new javax.swing.JTextField();
        jLabel142 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1057, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(58, 14, 18));
        jPanel2.setPreferredSize(new java.awt.Dimension(229, 590));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu_1.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 40, 40));

        Home_bar.setBackground(new java.awt.Color(58, 14, 18));
        Home_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home_barMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Home_barMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Home_barMouseExited(evt);
            }
        });
        Home_bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon home.png"))); // NOI18N
        Home_bar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 40));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Home");
        Home_bar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 60, 40));

        jPanel2.add(Home_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 40));

        Profile_bar.setBackground(new java.awt.Color(58, 14, 18));
        Profile_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Profile_barMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Profile_barMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Profile_barMouseExited(evt);
            }
        });
        Profile_bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon profile.png"))); // NOI18N
        Profile_bar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 40));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Profile");
        Profile_bar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 90, 40));

        jPanel2.add(Profile_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 230, 40));

        Balance_check_bar.setBackground(new java.awt.Color(58, 14, 18));
        Balance_check_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Balance_check_barMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Balance_check_barMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Balance_check_barMouseExited(evt);
            }
        });
        Balance_check_bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon balance.png"))); // NOI18N
        Balance_check_bar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 40));

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Balance Check");
        Balance_check_bar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 140, 40));

        jPanel2.add(Balance_check_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, 40));

        Loan_service_bar.setBackground(new java.awt.Color(58, 14, 18));
        Loan_service_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Loan_service_barMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Loan_service_barMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Loan_service_barMouseExited(evt);
            }
        });
        Loan_service_bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon loan.png"))); // NOI18N
        Loan_service_bar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 40));

        jLabel17.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Loan Services");
        Loan_service_bar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 130, 40));

        jPanel2.add(Loan_service_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 230, 40));

        Developer_bar.setBackground(new java.awt.Color(58, 14, 18));
        Developer_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Developer_barMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Developer_barMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Developer_barMouseExited(evt);
            }
        });
        Developer_bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon developer.png"))); // NOI18N
        Developer_bar.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 40));

        jLabel21.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Developer");
        Developer_bar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 100, 40));

        jPanel2.add(Developer_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 230, 40));

        Logout_bar.setBackground(new java.awt.Color(58, 14, 18));
        Logout_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_barMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Logout_barMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Logout_barMouseExited(evt);
            }
        });
        Logout_bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon logout.png"))); // NOI18N
        Logout_bar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 40));

        jLabel19.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Log out");
        Logout_bar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 90, 40));

        jPanel2.add(Logout_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, 40));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon admin1.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 120, 140));

        CalendarTextField.setEditable(false);
        CalendarTextField.setBackground(new java.awt.Color(58, 14, 18));
        CalendarTextField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        CalendarTextField.setForeground(new java.awt.Color(255, 255, 255));
        CalendarTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CalendarTextField.setBorder(null);
        jPanel2.add(CalendarTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 229, 620));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.CardLayout());

        HomePanel.setBackground(new java.awt.Color(255, 242, 221));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/22.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/66.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/11.png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/33.png"))); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/44.png"))); // NOI18N

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/55.png"))); // NOI18N

        jLabel27.setText("Bangladesh Bank");

        jLabel28.setText("easy Transaction");

        jLabel29.setText("Home Loan");

        jLabel30.setText("User Operating");

        jLabel32.setText("Business Loan");

        jLabel33.setText("Save your money");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel34.setText("BANKING MANAGEMENT SYSTEM");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel30)
                .addGap(136, 136, 136)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(HomePanelLayout.createSequentialGroup()
                            .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(HomePanelLayout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addGap(82, 82, 82)
                                    .addComponent(jLabel25)
                                    .addGap(97, 97, 97)
                                    .addComponent(jLabel26))
                                .addGroup(HomePanelLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(82, 82, 82)
                                    .addComponent(jLabel23)
                                    .addGap(97, 97, 97)
                                    .addComponent(jLabel12)))
                            .addGap(90, 90, 90))
                        .addGroup(HomePanelLayout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addComponent(jLabel27)
                            .addGap(129, 129, 129)
                            .addComponent(jLabel28)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29)
                            .addGap(130, 130, 130)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(198, 198, 198))))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel34)
                .addGap(74, 74, 74)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(28, 28, 28)
                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel24)))
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jPanel3.add(HomePanel, "card2");

        BalanceCheckPanel.setBackground(new java.awt.Color(255, 242, 221));

        jLabel62.setText("Thank you for banking with us.");

        jLabel63.setText("Copyright ©2022 BMS. All rights reserved.");

        jLabel8.setBackground(new java.awt.Color(58, 14, 18));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(58, 14, 18));
        jLabel8.setText("CURRENT BALANCE");

        TF_Balance.setBackground(new java.awt.Color(58, 14, 18));
        TF_Balance.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        TF_Balance.setForeground(new java.awt.Color(255, 255, 255));
        TF_Balance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_Balance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jButton1.setBackground(new java.awt.Color(58, 14, 18));
        jButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Check");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        CP_TF_PreAdd5.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_PreAdd5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_PreAdd5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CP_TF_PreAdd5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CP_TF_PreAdd5KeyTyped(evt);
            }
        });

        jLabel86.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel86.setText("Re-type Account No:");

        javax.swing.GroupLayout BalanceCheckPanelLayout = new javax.swing.GroupLayout(BalanceCheckPanel);
        BalanceCheckPanel.setLayout(BalanceCheckPanelLayout);
        BalanceCheckPanelLayout.setHorizontalGroup(
            BalanceCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BalanceCheckPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BalanceCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BalanceCheckPanelLayout.createSequentialGroup()
                        .addComponent(jLabel63)
                        .addGap(276, 276, 276))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BalanceCheckPanelLayout.createSequentialGroup()
                        .addGroup(BalanceCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(BalanceCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TF_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(BalanceCheckPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel86)
                                    .addGap(18, 18, 18)
                                    .addComponent(CP_TF_PreAdd5))))
                        .addGap(227, 227, 227))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BalanceCheckPanelLayout.createSequentialGroup()
                        .addComponent(jLabel62)
                        .addGap(316, 316, 316))))
        );
        BalanceCheckPanelLayout.setVerticalGroup(
            BalanceCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BalanceCheckPanelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(BalanceCheckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel86)
                    .addComponent(CP_TF_PreAdd5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addComponent(TF_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(jLabel62)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel63)
                .addContainerGap())
        );

        jPanel3.add(BalanceCheckPanel, "card2");

        DeveloperPanel.setBackground(new java.awt.Color(255, 242, 221));

        jLabel138.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel138.setText("Ahsanullah University of Science and Techmology");

        jLabel139.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel139.setText("Course No: CSE 2100");

        jLabel64.setText("Thank you for banking with us.");

        jLabel65.setText("Copyright ©2019 BMS. All rights reserved.");

        DeveloperPanel1.setBackground(new java.awt.Color(255, 242, 221));

        jLabel31.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel31.setText("Developer Panel");

        jLabel48.setText("Copyright ©2022 BMS. All rights reserved.");

        jLabel49.setText("Thank you for banking with us.");

        jLabel134.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel134.setText("Name: Faiyaz Al Islam");

        jLabel135.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel135.setText("ID: 20200104051");

        jLabel136.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel136.setText("Name: Hridita Barua");

        jLabel137.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel137.setText("ID: 20200104071");

        jLabel141.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel141.setText("Ahsanullah University of Science and Techmology");

        jLabel143.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel143.setText("Course No: CSE 2100");

        jLabel144.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel144.setText("Course Title: Software Development - II");

        jLabel149.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel149.setText("Name: Sowpnil Roy");

        jLabel151.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel151.setText("ID: 20200104052");

        javax.swing.GroupLayout DeveloperPanel1Layout = new javax.swing.GroupLayout(DeveloperPanel1);
        DeveloperPanel1.setLayout(DeveloperPanel1Layout);
        DeveloperPanel1Layout.setHorizontalGroup(
            DeveloperPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeveloperPanel1Layout.createSequentialGroup()
                .addGroup(DeveloperPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeveloperPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel31))
                    .addGroup(DeveloperPanel1Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel143))
                    .addGroup(DeveloperPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel141))
                    .addGroup(DeveloperPanel1Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel134))
                    .addGroup(DeveloperPanel1Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(DeveloperPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel144)
                            .addGroup(DeveloperPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel48))))
                    .addGroup(DeveloperPanel1Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel49))
                    .addGroup(DeveloperPanel1Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addGroup(DeveloperPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel136)
                            .addGroup(DeveloperPanel1Layout.createSequentialGroup()
                                .addGroup(DeveloperPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DeveloperPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel137))
                                    .addGroup(DeveloperPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel149)
                                        .addGroup(DeveloperPanel1Layout.createSequentialGroup()
                                            .addGroup(DeveloperPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel135)
                                                .addComponent(jLabel151, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(10, 10, 10))))
                                .addGap(7, 7, 7)))))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        DeveloperPanel1Layout.setVerticalGroup(
            DeveloperPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeveloperPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addGap(24, 24, 24)
                .addComponent(jLabel141)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel143)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel144)
                .addGap(35, 35, 35)
                .addComponent(jLabel134)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel135)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel136)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel151)
                .addGap(8, 8, 8)
                .addComponent(jLabel149)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel137)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addGap(280, 280, 280))
        );

        javax.swing.GroupLayout DeveloperPanelLayout = new javax.swing.GroupLayout(DeveloperPanel);
        DeveloperPanel.setLayout(DeveloperPanelLayout);
        DeveloperPanelLayout.setHorizontalGroup(
            DeveloperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeveloperPanelLayout.createSequentialGroup()
                .addGroup(DeveloperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeveloperPanelLayout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel139))
                    .addGroup(DeveloperPanelLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel138)))
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeveloperPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(DeveloperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeveloperPanelLayout.createSequentialGroup()
                        .addComponent(jLabel65)
                        .addGap(273, 273, 273))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeveloperPanelLayout.createSequentialGroup()
                        .addComponent(jLabel64)
                        .addGap(315, 315, 315))))
            .addGroup(DeveloperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DeveloperPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(DeveloperPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        DeveloperPanelLayout.setVerticalGroup(
            DeveloperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeveloperPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel138)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel139)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 651, Short.MAX_VALUE)
                .addComponent(jLabel64)
                .addGap(18, 18, 18)
                .addComponent(jLabel65)
                .addContainerGap())
            .addGroup(DeveloperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DeveloperPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(DeveloperPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(DeveloperPanel, "card2");

        CP_Panel.setBackground(new java.awt.Color(255, 242, 221));

        jLabel69.setText("Copyright ©2022 BMS. All rights reserved.");

        jLabel70.setText("Thank you for banking with us.");

        jLabel71.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel71.setText("Account Type:");

        jLabel72.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel72.setText("Account No:");

        jLabel73.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel73.setText("Account Title:");

        jLabel74.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel74.setText("Account Holder:");

        jLabel75.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel75.setText("Contact No:");

        jLabel76.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel76.setText("Gender:");

        jLabel77.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel77.setText("Nationality:");

        CP_TF_AccNo.setEditable(false);
        CP_TF_AccNo.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_AccNo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_AccNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CP_TF_AccTitle.setEditable(false);
        CP_TF_AccTitle.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_AccTitle.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_AccTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CP_TF_AccHolder.setEditable(false);
        CP_TF_AccHolder.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_AccHolder.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_AccHolder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CP_TF_ContNo.setEditable(false);
        CP_TF_ContNo.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_ContNo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_ContNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CP_TF_Nationality.setEditable(false);
        CP_TF_Nationality.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_Nationality.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_Nationality.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel78.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel78.setText("Date of Birth: ");

        jLabel79.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel79.setText("Present Address:");

        jLabel80.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel80.setText("Parmanent Address:");

        jLabel81.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel81.setText("Currency:");

        jLabel82.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel82.setText("Current Balance:");

        jLabel83.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel83.setText("Secuirty Question:");

        jLabel84.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel84.setText("Answer:");

        CP_TF_Balance.setEditable(false);
        CP_TF_Balance.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_Balance.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_Balance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CP_TF_SA.setEditable(false);
        CP_TF_SA.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_SA.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_SA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CP_TF_SA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CP_TF_SAActionPerformed(evt);
            }
        });

        CP_TF_ParAdd.setEditable(false);
        CP_TF_ParAdd.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_ParAdd.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_ParAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CP_TF_PreAdd.setEditable(false);
        CP_TF_PreAdd.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_PreAdd.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_PreAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CP_TF_AccNo1.setEditable(false);
        CP_TF_AccNo1.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_AccNo1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_AccNo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CP_TF_AccNo2.setEditable(false);
        CP_TF_AccNo2.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_AccNo2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_AccNo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CP_TF_PreAdd1.setEditable(false);
        CP_TF_PreAdd1.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_PreAdd1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_PreAdd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CP_TF_PreAdd2.setEditable(false);
        CP_TF_PreAdd2.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_PreAdd2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_PreAdd2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CP_TF_PreAdd3.setEditable(false);
        CP_TF_PreAdd3.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_PreAdd3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_PreAdd3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel85.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel85.setText("Re-type Account No:");

        CP_TF_PreAdd4.setBackground(new java.awt.Color(255, 242, 221));
        CP_TF_PreAdd4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        CP_TF_PreAdd4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CP_TF_PreAdd4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CP_TF_PreAdd4KeyTyped(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(58, 14, 18));
        jButton2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Check");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CP_PanelLayout = new javax.swing.GroupLayout(CP_Panel);
        CP_Panel.setLayout(CP_PanelLayout);
        CP_PanelLayout.setHorizontalGroup(
            CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CP_PanelLayout.createSequentialGroup()
                .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CP_PanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(CP_PanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel77)
                            .addComponent(jLabel71)
                            .addComponent(jLabel72)
                            .addComponent(jLabel73)
                            .addComponent(jLabel74)
                            .addComponent(jLabel75)
                            .addComponent(jLabel76))
                        .addGap(18, 18, 18)
                        .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CP_TF_AccHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CP_TF_Nationality)
                                .addComponent(CP_TF_AccNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CP_TF_AccTitle)
                                .addComponent(CP_TF_AccNo1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CP_TF_AccNo2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(CP_TF_ContNo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel79)
                            .addComponent(jLabel78)
                            .addComponent(jLabel80)
                            .addComponent(jLabel81)
                            .addComponent(jLabel82)
                            .addComponent(jLabel83)
                            .addComponent(jLabel84)
                            .addComponent(jLabel85))
                        .addGap(18, 18, 18)
                        .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CP_TF_PreAdd4)
                            .addComponent(CP_TF_Balance, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(CP_TF_SA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CP_TF_PreAdd)
                            .addComponent(CP_TF_ParAdd)
                            .addComponent(CP_TF_PreAdd1)
                            .addComponent(CP_TF_PreAdd2)
                            .addComponent(CP_TF_PreAdd3))))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CP_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CP_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel70)
                        .addGap(317, 317, 317))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CP_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel69)
                        .addGap(274, 274, 274))))
        );
        CP_PanelLayout.setVerticalGroup(
            CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CP_PanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel85)
                    .addComponent(CP_TF_PreAdd4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CP_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel71)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel72)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel73)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel74)
                        .addGap(35, 35, 35)
                        .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel75)
                            .addComponent(CP_TF_ContNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel76)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel77))
                    .addGroup(CP_PanelLayout.createSequentialGroup()
                        .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CP_PanelLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(CP_TF_AccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(CP_TF_AccTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CP_PanelLayout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(CP_TF_AccHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(130, 130, 130)
                        .addComponent(CP_TF_Nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CP_PanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(CP_TF_PreAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CP_PanelLayout.createSequentialGroup()
                        .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel78)
                            .addComponent(CP_TF_AccNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CP_TF_PreAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel79)
                        .addGap(36, 36, 36)
                        .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel80)
                            .addComponent(CP_TF_ParAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel81)
                            .addComponent(CP_TF_PreAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel82)
                            .addComponent(CP_TF_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel83)
                            .addComponent(CP_TF_PreAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CP_TF_AccNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(CP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel84)
                            .addComponent(CP_TF_SA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(92, 92, 92)
                .addComponent(jLabel70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel69)
                .addContainerGap())
        );

        jPanel3.add(CP_Panel, "card2");

        RS_Panel.setBackground(new java.awt.Color(255, 242, 221));

        jLabel118.setText("Thank you for banking with us.");

        jLabel119.setText("Copyright ©2022 BMS. All rights reserved.");

        jLabel121.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel121.setText("Account Title:");

        jLabel122.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel122.setText("Contact No:");

        jLabel123.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel123.setText("Current Balance:");

        jLabel124.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel124.setText("Remaining Payment:");

        RS_AccTitle.setEditable(false);
        RS_AccTitle.setBackground(new java.awt.Color(255, 242, 221));
        RS_AccTitle.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        RS_AccTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        RS_ContNo.setEditable(false);
        RS_ContNo.setBackground(new java.awt.Color(255, 242, 221));
        RS_ContNo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        RS_ContNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        RS_Balance.setEditable(false);
        RS_Balance.setBackground(new java.awt.Color(255, 242, 221));
        RS_Balance.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        RS_Balance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        RS_RP.setEditable(false);
        RS_RP.setBackground(new java.awt.Color(255, 242, 221));
        RS_RP.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        RS_RP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        BTN_Submit22.setBackground(new java.awt.Color(56, 86, 34));
        BTN_Submit22.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        BTN_Submit22.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Submit22.setText("SUBMIT");
        BTN_Submit22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_Submit22MouseClicked(evt);
            }
        });

        jLabel131.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel131.setText("Amount of Stepend: ");

        RS_Stepend.setEditable(false);
        RS_Stepend.setBackground(new java.awt.Color(255, 242, 221));
        RS_Stepend.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        RS_Stepend.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        RS_AccNo.setBackground(new java.awt.Color(255, 242, 221));
        RS_AccNo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        RS_AccNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel142.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel142.setText("Re-type Account No:");

        jButton3.setBackground(new java.awt.Color(56, 86, 34));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ok");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RS_PanelLayout = new javax.swing.GroupLayout(RS_Panel);
        RS_Panel.setLayout(RS_PanelLayout);
        RS_PanelLayout.setHorizontalGroup(
            RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RS_PanelLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(RS_PanelLayout.createSequentialGroup()
                        .addGroup(RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel131)
                            .addComponent(jLabel123)
                            .addComponent(jLabel121)
                            .addComponent(jLabel122)
                            .addComponent(jLabel124)
                            .addComponent(jLabel142))
                        .addGap(35, 35, 35)
                        .addGroup(RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RS_AccNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(RS_RP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(RS_Balance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(RS_ContNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(RS_AccTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(RS_Stepend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(BTN_Submit22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(260, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RS_PanelLayout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addGroup(RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RS_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel118)
                        .addGap(314, 314, 314))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RS_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel119)
                        .addGap(276, 276, 276))))
        );
        RS_PanelLayout.setVerticalGroup(
            RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RS_PanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel142)
                    .addComponent(RS_AccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(23, 23, 23)
                .addGroup(RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RS_PanelLayout.createSequentialGroup()
                        .addGroup(RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RS_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel123))
                        .addGap(36, 36, 36)
                        .addGroup(RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RS_RP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel124))
                        .addGap(29, 29, 29)
                        .addGroup(RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RS_Stepend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel131)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RS_PanelLayout.createSequentialGroup()
                        .addGroup(RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel121)
                            .addComponent(RS_AccTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel122)
                            .addComponent(RS_ContNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(167, 167, 167)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(BTN_Submit22)
                .addGap(109, 109, 109)
                .addComponent(jLabel118)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel119)
                .addContainerGap())
        );

        jPanel3.add(RS_Panel, "card2");

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 95, 830, 625));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu_1.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/main frame1111.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int x =229;
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(x==229){
            jPanel2.setSize(229, 620);
            Thread th = new Thread(){
                public void run(){
                    try{
                        for(int i= 229; i>=0;i--){
                            Thread.sleep(1);
                            jPanel2.setSize(i,620);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);
                    }
                }
            };th.start();
            x=0;
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        labelcolor(jLabel1);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        resetlabelcolor(jLabel1);
    }//GEN-LAST:event_jLabel1MouseExited

    private void Home_barMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_barMouseClicked
        // resret panel color
        resetpanelcolor(jPanel1);
        resetpanelcolor(jPanel2);
        resetpanelcolor(jPanel3);
        resetpanelcolor(Profile_bar);
        //resetpanelcolor(jPanel5);
        
        
        resetpanelcolor(Balance_check_bar);
        resetpanelcolor(Loan_service_bar);
        resetpanelcolor(Logout_bar);
        resetpanelcolor(Developer_bar);

        // set panelc  color
        panelcolor(Home_bar);

        //remove panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        // add panel
        jPanel3.add(HomePanel);
        jPanel3.repaint();
        jPanel3.revalidate();

    }//GEN-LAST:event_Home_barMouseClicked

    private void Home_barMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_barMouseEntered
        // barlcolor(Home_bar);
    }//GEN-LAST:event_Home_barMouseEntered

    private void Home_barMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_barMouseExited
        //resetbarlcolor(Home_bar);
    }//GEN-LAST:event_Home_barMouseExited

    private void Balance_check_barMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Balance_check_barMouseClicked
        // resret panel color
        resetpanelcolor(jPanel1);
        resetpanelcolor(jPanel2);
        resetpanelcolor(jPanel3);
        resetpanelcolor(Profile_bar);
        resetpanelcolor(Home_bar);
        
        
        //resetpanelcolor(jPanel9);
        resetpanelcolor(Loan_service_bar);
        resetpanelcolor(Logout_bar);
        resetpanelcolor(Developer_bar);

        // set panelc  color
        panelcolor(Balance_check_bar);

        //remove panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        // add panel
        jPanel3.add(BalanceCheckPanel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_Balance_check_barMouseClicked

    private void Balance_check_barMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Balance_check_barMouseEntered
        //barlcolor(Balance_check_bar);
    }//GEN-LAST:event_Balance_check_barMouseEntered

    private void Balance_check_barMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Balance_check_barMouseExited
        //resetbarlcolor(Balance_check_bar);
    }//GEN-LAST:event_Balance_check_barMouseExited

    private void Loan_service_barMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Loan_service_barMouseClicked
        // resret panel color
        resetpanelcolor(jPanel1);
        resetpanelcolor(jPanel2);
        resetpanelcolor(jPanel3);
        resetpanelcolor(Profile_bar);
        resetpanelcolor(Home_bar);
        
        
        resetpanelcolor(Balance_check_bar);
        //resetpanelcolor(jPanel10);
        resetpanelcolor(Logout_bar);
        resetpanelcolor(Developer_bar);

        // set panelc  color
        panelcolor(Loan_service_bar);

        //remove panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        // add panel
        jPanel3.add(RS_Panel);
        jPanel3.repaint();
        jPanel3.revalidate();
        
       
    }//GEN-LAST:event_Loan_service_barMouseClicked

    private void Loan_service_barMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Loan_service_barMouseEntered
        //barlcolor(Loan_service_bar);
    }//GEN-LAST:event_Loan_service_barMouseEntered

    private void Loan_service_barMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Loan_service_barMouseExited
        //resetbarlcolor(Loan_service_bar);
    }//GEN-LAST:event_Loan_service_barMouseExited

    private void Developer_barMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Developer_barMouseClicked
        // resret panel color
        resetpanelcolor(jPanel1);
        resetpanelcolor(jPanel2);
        resetpanelcolor(jPanel3);
        resetpanelcolor(Profile_bar);
        resetpanelcolor(Home_bar);
        
        
        resetpanelcolor(Balance_check_bar);
        resetpanelcolor(Loan_service_bar);
        resetpanelcolor(Logout_bar);
        //resetpanelcolor(jPanel12);

        // set panelc  color
        panelcolor(Developer_bar);

        //remove panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        // add panel
        jPanel3.add(DeveloperPanel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_Developer_barMouseClicked

    private void Developer_barMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Developer_barMouseEntered
        //barlcolor(Developer_bar);
    }//GEN-LAST:event_Developer_barMouseEntered

    private void Developer_barMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Developer_barMouseExited
        //resetbarlcolor(Developer_bar);
    }//GEN-LAST:event_Developer_barMouseExited

    private void Logout_barMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_barMouseClicked
        // resret panel color
        resetpanelcolor(jPanel1);
        resetpanelcolor(jPanel2);
        resetpanelcolor(jPanel3);
        resetpanelcolor(Profile_bar);
        resetpanelcolor(Home_bar);
        
        
        resetpanelcolor(Balance_check_bar);
        resetpanelcolor(Loan_service_bar);
        resetpanelcolor(Logout_bar);
        resetpanelcolor(Developer_bar);

        // set panelc  color
        panelcolor(Logout_bar);
        /*
        //remove panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        // add panel
        jPanel3.add(DepositPanel);
        jPanel3.repaint();
        jPanel3.revalidate();
        */
        int choice = JOptionPane.showConfirmDialog(null,"Do you want to logout?","Logout",JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION)
        {
            UserLoginFrame lf = new UserLoginFrame();
            lf.setVisible(true);
            lf.pack();
            lf.setLocationRelativeTo(null);
            this.dispose();
        }

    }//GEN-LAST:event_Logout_barMouseClicked

    private void Logout_barMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_barMouseEntered
        //barlcolor(Logout_bar);
    }//GEN-LAST:event_Logout_barMouseEntered

    private void Logout_barMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_barMouseExited
        // resetbarlcolor(Logout_bar);
    }//GEN-LAST:event_Logout_barMouseExited

    private void CP_TF_SAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CP_TF_SAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CP_TF_SAActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if(x==0){
            jPanel2.show();
            jPanel2.setSize(x, 620);
            Thread th = new Thread(){
                public void run(){
                    try{
                        for(int i= 0; i<=x;i++){
                            Thread.sleep(1);
                            jPanel2.setSize(i,620);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);
                    }
                }
            };th.start();
            x=229;
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        labelcolor(jLabel3);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        resetlabelcolor(jLabel3);
    }//GEN-LAST:event_jLabel3MouseExited

    private void Profile_barMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_barMouseExited
        //resetbarlcolor(Profile_bar);
    }//GEN-LAST:event_Profile_barMouseExited

    private void Profile_barMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_barMouseEntered
        //barlcolor(Profile_bar);
    }//GEN-LAST:event_Profile_barMouseEntered

    private void Profile_barMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_barMouseClicked
        // resret panel color
        resetpanelcolor(jPanel1);
        resetpanelcolor(jPanel2);
        resetpanelcolor(jPanel3);
        //resetpanelcolor(jPanel4);
        resetpanelcolor(Home_bar);
        
        resetpanelcolor(Balance_check_bar);
        resetpanelcolor(Loan_service_bar);
        resetpanelcolor(Logout_bar);
        resetpanelcolor(Developer_bar);

        // set panelc  color
        panelcolor(Profile_bar);

        //remove panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        // add panel
        jPanel3.add(CP_Panel);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        
    }//GEN-LAST:event_Profile_barMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String query = "select * from Customer where ACNo = ?";
        String AccountNo = CP_TF_PreAdd5.getText();
        try {
            st = Database_Connection.getConnectoin().prepareStatement(query);
            st.setString(1, AccountNo);
            rs = st.executeQuery();
            if(rs.next())
            {
                
                String add3 = rs.getString("Balance");
                TF_Balance.setText("TK. "+add3);
                
                rs.close();
                st.close();
            }else{
                JOptionPane.showMessageDialog(null, "Enter correct A/C No.","Invalid Account No",2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try {
                rs.close();
                st.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        
    }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String acc = CP_TF_PreAdd4.getText();
        
        
        // create a select query to check if the username and the password exist in the database
        String query = "SELECT * FROM `customer`WHERE `ACNo` = ?  ";
        try {
            st = Database_Connection.getConnectoin().prepareStatement(query);
            
            st.setString(1, acc);
 
            rs = st.executeQuery();
            
            if (rs.next()){
                //remove panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        // add panel
        jPanel3.add(CP_Panel);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        CP_TF_AccNo.setText(acc);
        
        String Type = rs.getString("ACType");
        CP_TF_AccNo1.setText(Type);
        String Title = rs.getString("ACTitle");
        CP_TF_AccTitle.setText(Title);
        String Holder = rs.getString("ACHolder");
        CP_TF_AccHolder.setText(Holder);
        String contNo = rs.getString("ContactNo");
        CP_TF_ContNo.setText(contNo);
        
        String Gen = rs.getString("Gender");
        CP_TF_AccNo2.setText(Gen);
        
        
        String Nationality = rs.getString("Nationality");
        CP_TF_Nationality.setText(Nationality);
        String DoB = rs.getString("DOB");
        CP_TF_PreAdd1.setText(DoB);
        
        String PreAddress = rs.getString("PreAdd");
        CP_TF_PreAdd.setText(PreAddress);
        
        String ParAddress = rs.getString("ParAdd");
        CP_TF_ParAdd.setText(ParAddress);
     
        String Curr = rs.getString("Currency");
        CP_TF_PreAdd2.setText(Curr);
        
        String CurrBal = rs.getString("Balance");
        CP_TF_Balance.setText(CurrBal);
        
        String SecQue = rs.getString("SQ");
        CP_TF_PreAdd3.setText(SecQue);
        
        String SecAns = rs.getString("SQans");
        CP_TF_SA.setText(SecAns);
        
        
        
        
        
            }else{
                //Show error message
                JOptionPane.showMessageDialog(null, "Invalid A/C No.","error",2);
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_jButton2MouseClicked

    private void CP_TF_PreAdd5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CP_TF_PreAdd5KeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_CP_TF_PreAdd5KeyTyped

    private void CP_TF_PreAdd4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CP_TF_PreAdd4KeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_CP_TF_PreAdd4KeyTyped

    private void BTN_Submit22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_Submit22MouseClicked
        String Acc = RS_AccNo.getText();

        String currBal = RS_Balance.getText();
        float bal = Float.parseFloat(currBal);
        String remLoan = RS_RP.getText();
        float rem = Float.parseFloat(remLoan);
        String stepend = RS_Stepend.getText();
        float step = Float.parseFloat(stepend);

        float remLoanAfterPayment = rem - step;
        float remBalAfterPayment = bal - step;

        String query = "update customer set Balance = ' "+remBalAfterPayment+"' where ACNo = '"+Acc+"'";
        String query1 = "update loanservice set TotalPayment = ' "+remLoanAfterPayment+"' where AccNo = '"+Acc+"'";
        if(remBalAfterPayment>=500){
            try {
                st = Database_Connection.getConnectoin().prepareStatement(query);
                st.execute();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            try {
                st = Database_Connection.getConnectoin().prepareStatement(query1);
                st.execute();
                JOptionPane.showMessageDialog(null, "Paid successfully.\nCurrent Balance is = Tk."+remBalAfterPayment +"\nRemaining Payment is = Tk."+remLoanAfterPayment,"Payment",2);
                RS_AccNo.setText("");
                RS_AccTitle.setText("");
                RS_ContNo.setText("");
                RS_Balance.setText("");
                RS_RP.setText("");
                RS_Stepend.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Insufficient Balance\n Please, deposit & pay.","Error",2);
        }
        
        
    }//GEN-LAST:event_BTN_Submit22MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String acc = RS_AccNo.getText();
        
        
        // create a select query to check if the username and the password exist in the database
        if(acc.trim().equals("") ){
            JOptionPane.showMessageDialog(null, "Please fill the required fields.","Login error",2);
        }else{
        String query = "SELECT * FROM `customer`WHERE `ACNo` = ? ";
        try {
            st = Database_Connection.getConnectoin().prepareStatement(query);
            
            st.setString(1, acc);
            
            rs = st.executeQuery();
            
            if (rs.next()){
                
        
        String Title = rs.getString("ACTitle");
        RS_AccTitle.setText(Title);
        String contNo = rs.getString("ContactNo");
        RS_ContNo.setText(contNo);
        
        String CurrentBalance = rs.getString("Balance");
        RS_Balance.setText(CurrentBalance);
        }else{
                //Show error message
                JOptionPane.showMessageDialog(null, "Invalid A/C No or Contact No.","Login error",2);
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        String query1 = "SELECT * FROM `loanservice`WHERE `AccNo` = ? ";
        try {
            st = Database_Connection.getConnectoin().prepareStatement(query1);
            
            st.setString(1, acc);
            
            rs = st.executeQuery();
            
            if (rs.next()){
        
        String RemainingPayment = rs.getString("TotalPayment");
        RS_RP.setText(RemainingPayment);
        
        String Stepend = rs.getString("MonthlyStepend");
        RS_Stepend.setText(Stepend);
        }
        } catch (SQLException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Submit22;
    private javax.swing.JPanel BalanceCheckPanel;
    private javax.swing.JPanel Balance_check_bar;
    private javax.swing.JPanel CP_Panel;
    private javax.swing.JTextField CP_TF_AccHolder;
    private javax.swing.JTextField CP_TF_AccNo;
    private javax.swing.JTextField CP_TF_AccNo1;
    private javax.swing.JTextField CP_TF_AccNo2;
    private javax.swing.JTextField CP_TF_AccTitle;
    private javax.swing.JTextField CP_TF_Balance;
    private javax.swing.JTextField CP_TF_ContNo;
    private javax.swing.JTextField CP_TF_Nationality;
    private javax.swing.JTextField CP_TF_ParAdd;
    private javax.swing.JTextField CP_TF_PreAdd;
    private javax.swing.JTextField CP_TF_PreAdd1;
    private javax.swing.JTextField CP_TF_PreAdd2;
    private javax.swing.JTextField CP_TF_PreAdd3;
    private javax.swing.JTextField CP_TF_PreAdd4;
    private javax.swing.JTextField CP_TF_PreAdd5;
    private javax.swing.JTextField CP_TF_SA;
    private javax.swing.JTextField CalendarTextField;
    private javax.swing.JPanel DeveloperPanel;
    private javax.swing.JPanel DeveloperPanel1;
    private javax.swing.JPanel Developer_bar;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel Home_bar;
    private javax.swing.JPanel Loan_service_bar;
    private javax.swing.JPanel Logout_bar;
    private javax.swing.JPanel Profile_bar;
    private javax.swing.JTextField RS_AccNo;
    private javax.swing.JTextField RS_AccTitle;
    private javax.swing.JTextField RS_Balance;
    private javax.swing.JTextField RS_ContNo;
    private javax.swing.JPanel RS_Panel;
    private javax.swing.JTextField RS_RP;
    private javax.swing.JTextField RS_Stepend;
    private javax.swing.JTextField TF_Balance;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    // set and reset panel color functions
    private void panelcolor (JPanel panel){
            panel.setBackground(new java.awt.Color(53, 162, 107));
        }
    private void resetpanelcolor (JPanel panel){
            panel.setBackground(new java.awt.Color(58,14,18));
        }
    
    // set and reset bar color functions
    
    private void barlcolor (JPanel panel){
            panel.setBackground(new java.awt.Color(53, 162, 107));
        }
    private void resetbarlcolor (JPanel panel){
            panel.setBackground(new java.awt.Color(54, 70, 78));
        }
    
    
    // set and reset label color functions
    
    private void labelcolor (JLabel lebel){
            lebel.setBackground(new java.awt.Color(53, 162, 107));
        }
    private void resetlabelcolor (JLabel lebel){
            lebel.setBackground(new java.awt.Color(54, 70, 78));
        }
    
     // set and reset button color functions
    
    private void buttoncolor (JButton button){
            button.setBackground(new java.awt.Color(65,101,41));
        }
    private void resetbuttoncolor (JButton button){
            button.setBackground(new java.awt.Color(56,86,34));
        }
    
    // date: Auto update function
    public void setCalendar(){
        Calendar cal = new GregorianCalendar();
         int dd = cal.get(Calendar.DAY_OF_MONTH);
         int mm = cal.get(Calendar.MONTH);
         int yy = cal.get(Calendar.YEAR);
         CalendarTextField.setText("Date: "+dd+" / "+(mm+1)+" / "+yy);
    }
   
}
